# Generated by Django 4.2.27 on 2026-01-15 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_storefront_show_empty_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_name',
            field=models.CharField(blank=True, help_text='Origin source for imported product data (e.g., Traction).', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source_product_id',
            field=models.CharField(blank=True, help_text='Source product identifier from the import origin.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, help_text='Source URL for imported product data.', null=True),
        ),
        migrations.CreateModel(
            name='ProductAlternateSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('interchange', 'Interchange'), ('equivalent', 'Equivalent'), ('alternate', 'Alternate'), ('oem', 'OEM')], default='interchange', max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_skus', to='accounts.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productalternatesku',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), models.F('product'), name='unique_alternate_sku_per_product'),
        ),
    ]
