# Generated by Codex on 2026-01-19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_storefront_flyer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectedBusinessGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=120)),
                ("share_customers", models.BooleanField(default=True, help_text="Share customers (and related lists) across connected businesses.")),
                ("share_products", models.BooleanField(default=False, help_text="Share products and inventory across connected businesses.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("members", models.ManyToManyField(blank=True, related_name="connected_business_groups", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Connected business group",
                "verbose_name_plural": "Connected business groups",
            },
        ),
    ]
