# Generated by Codex on 2026-01-20

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_connected_business_group_share_product_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorefrontCartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="storefront_cart_items", to="accounts.customer")),
                ("store_owner", models.ForeignKey(help_text="Storefront location the item was added from.", on_delete=django.db.models.deletion.CASCADE, related_name="storefront_cart_items", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="storefront_cart_items", to="accounts.product")),
            ],
            options={
                "unique_together": {("customer", "store_owner", "product")},
            },
        ),
    ]
