# Generated by Codex on 2026-01-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_product_core_and_env_and_invoice_line_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorefrontFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="storefront_favorites", to="accounts.customer")),
                ("store_owner", models.ForeignKey(help_text="Storefront location the favorite belongs to.", on_delete=django.db.models.deletion.CASCADE, related_name="storefront_favorites", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="storefront_favorites", to="accounts.product")),
            ],
            options={
                "unique_together": {("customer", "store_owner", "product")},
            },
        ),
    ]
