# Generated by Codex on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_storefront_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products suggested alongside this part on the storefront.",
                related_name="related_to_products",
                symmetrical=False,
                to="accounts.product",
            ),
        ),
    ]
