# Generated by Codex on 2026-01-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_product_related_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="related_products",
        ),
        migrations.CreateModel(
            name="StorefrontJobBundle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job_name", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="storefront_job_bundles", to="accounts.servicejobname")),
                ("products", models.ManyToManyField(blank=True, related_name="storefront_job_bundles", to="accounts.product")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="storefront_job_bundles", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="StorefrontKit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kit_type",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance kit"),
                            ("seasonal", "Seasonal kit"),
                            ("dot", "DOT inspection kit"),
                            ("custom", "Custom kit"),
                        ],
                        default="maintenance",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("products", models.ManyToManyField(blank=True, related_name="storefront_kits", to="accounts.product")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="storefront_kits", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="StorefrontCategoryCrossSell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=140)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="storefront_cross_sells", to="accounts.category")),
                ("products", models.ManyToManyField(blank=True, related_name="storefront_cross_sells", to="accounts.product")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="storefront_category_cross_sells", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["category__name"],
            },
        ),
        migrations.CreateModel(
            name="ProductInstallEssential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=160)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="install_essentials", to="accounts.product")),
                ("related_product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="install_essential_links", to="accounts.product")),
            ],
            options={
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="StorefrontCoreChargePolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="Core charge policy", max_length=160)),
                ("summary", models.TextField(blank=True)),
                ("refund_timeline_days", models.PositiveIntegerField(default=30)),
                ("policy_file", models.FileField(blank=True, null=True, upload_to="storefront_policies/")),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="storefront_core_policy", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="storefrontcategorycrosssell",
            constraint=models.UniqueConstraint(fields=("user", "category"), name="unique_storefront_cross_sell_category"),
        ),
    ]
