# Generated by Django 4.2.27 on 2026-02-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_normalize_media_file_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_value',
            field=models.CharField(blank=True, db_index=True, help_text='Scannable barcode value (UPC/EAN/Code128) for this part.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fitment_notes',
            field=models.TextField(blank=True, help_text='Fitment notes such as axle position, year range, or trim compatibility.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='oem_part_number',
            field=models.CharField(blank=True, db_index=True, help_text='Primary OEM part number used for cross-reference lookups.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productstock',
            name='max_stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
