# Generated by Django 4.2.27 on 2026-02-08 23:40

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_product_barcode_value_product_fitment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetPartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fleet_part_lists', to=settings.AUTH_USER_MODEL)),
                ('fleet_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_part_lists', to='accounts.fleetvehicle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_part_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('partially_received', 'Partially received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('ordered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='accounts.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierScorecardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.localdate)),
                ('period_days', models.PositiveIntegerField(default=90)),
                ('po_count', models.PositiveIntegerField(default=0)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('fill_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('avg_lead_time_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('rma_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('weighted_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_snapshots', to='accounts.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_scorecard_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date', 'supplier__name'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_time_days', models.PositiveIntegerField(default=7)),
                ('coverage_days', models.PositiveIntegerField(default=30)),
                ('buffer_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('min_order_qty', models.PositiveIntegerField(default=0)),
                ('order_multiple', models.PositiveIntegerField(default=1)),
                ('seasonality_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('auto_generate_po', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_rules', to='accounts.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField(default=0)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('recommended_quantity', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='accounts.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.purchaseorder')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductRMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('rma_type', models.CharField(choices=[('core', 'Core return'), ('warranty', 'Warranty'), ('return', 'Return')], default='core', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received'), ('credited', 'Credited'), ('closed', 'Closed')], default='open', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField(blank=True)),
                ('supplier_reference', models.CharField(blank=True, max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('expected_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_adjusted', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_rmas', to='accounts.customer')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_rmas', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_entries', to='accounts.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_entries', to='accounts.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rmas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='MarginGuardrailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('warning_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('enforce_min_margin', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='margin_guardrail_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Margin guardrail',
                'verbose_name_plural': 'Margin guardrails',
            },
        ),
        migrations.CreateModel(
            name='InventoryRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('buyer', 'Buyer'), ('warehouse', 'Warehouse'), ('sales', 'Sales'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_role_assignments', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_assigned_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['member__username'],
            },
        ),
        migrations.CreateModel(
            name='FleetPartListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('install_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('install_interval_km', models.PositiveIntegerField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('part_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.fleetpartlist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_part_list_items', to='accounts.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='DispatchTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('destination_name', models.CharField(max_length=180)),
                ('destination_address', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('vehicle_reference', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('dispatched', 'Dispatched'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('tracking_notes', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatch_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_tickets', to='accounts.customer')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_tickets', to='accounts.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_tickets', to='accounts.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Cycle Count', max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cycle_counts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_count_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField(default=0)),
                ('counted_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('variance', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_count_entries', to='accounts.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.cyclecountsession')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierscorecardsnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'supplier', 'snapshot_date', 'period_days'), name='unique_supplier_scorecard_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='replenishmentrule',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_replenishment_rule_per_product'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'product'), name='unique_purchase_order_item_per_product'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('po_number'), models.F('user'), condition=models.Q(('po_number__isnull', False), models.Q(('po_number', ''), _negated=True)), name='unique_purchase_order_number_per_user'),
        ),
        migrations.AddConstraint(
            model_name='inventoryroleassignment',
            constraint=models.UniqueConstraint(fields=('business', 'member'), name='unique_inventory_role_assignment_per_member'),
        ),
        migrations.AddConstraint(
            model_name='fleetpartlistitem',
            constraint=models.UniqueConstraint(fields=('part_list', 'product'), name='unique_fleet_list_item_per_product'),
        ),
        migrations.AddConstraint(
            model_name='fleetpartlist',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_fleet_part_list_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cyclecountentry',
            constraint=models.UniqueConstraint(fields=('session', 'product'), name='unique_cycle_count_entry_per_product'),
        ),
    ]
